policyImage:
  registry: ghcr.io/rancherfederal/policies/rancher-project-mapper
  tag: latest

policy:
  mode: protect

policyServer:
  create: true
  replicas: 3

  # If storing your policy in a private OCI registry, you need to create the secret first in the 'kubewarden' namespace.
  # See here for more info: https://docs.kubewarden.io/operator-manual/policy-servers/private-registry
  # imagePullSecret: "" 

  # If create is false, specify existing policyServer name.
  name: default

settings:
  clusterName: foobar
  projects:
  - match_type: exact
    project_name: boop
    namespace_match: boop
