{{- if .Values.policyServer.create }}
apiVersion: policies.kubewarden.io/v1
kind: PolicyServer
metadata:
  name: namespace-mapper-ps
spec:
  env:
    - name: KUBEWARDEN_LOG_LEVEL
      value: info
  image: ghcr.io/kubewarden/policy-server:v1.5.3
  replicas: {{ .Values.policyServer.replicas }}
  serviceAccountName: policy-server
  {{- if .Values.policyServer.imagePullSecret }}
  imagePullSecret: {{ .Values.policyServer.imagePullSecret }}
  {{- end }}
{{- end }}