kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: rancher-project-mapper
  namespace: fleet-default
spec:
  repo: https://github.com/rancherfederal/rancher-project-mapper.git
  branch: main
targets:
  - clusterSelector: {} # Deploy to all clusters
  paths:
  - ./fleet/helm