{{- if .Values.policyServer.create }}
apiVersion: policies.kubewarden.io/v1
kind: PolicyServer
metadata:
  name: namespace-mapper-ps
spec:
  env:
    - name: KUBEWARDEN_LOG_LEVEL
      value: info
  image: ghcr.io/kubewarden/policy-server:{{ .Values.policyServer.imageTag }}
  replicas: {{ .Values.policyServer.replicas }}
  {{- if .Values.policyServer.imagePullSecret }}
  imagePullSecret: {{ .Values.policyServer.imagePullSecret }}
  {{- end }}
{{- end }}