defaultNamespace: kubewarden

labels:
  app: rancher-project-mapper

helm:
  chart: ./chart
  valueFiles:
  - values.yaml

dependsOn:
  - selector:
      matchLabels:
        app: kubewarden-controller