on:
  push:
    branches:
    - main
    - master
    tags:
    - 'v*'

name: Release policy

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@v1
      -
        name: Build and annotate policy
        uses: kubewarden/github-actions/policy-build-rust@v1
        with:
          input-wasm: target/wasm32-wasi/release/kubewarden_namespace_mapper_policy.wasm
      # -
      #   name: Run e2e tests
      #   run: |
      #     make e2e-tests
      -
        name: Release
        uses: kubewarden/github-actions/policy-release@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          oci-target: ghcr.io/atoy3731/policies/namespace-mapper
          workflow-pat: ${{ secrets.WORKFLOW_PAT }}
          annotated-wasm: annotated-policy.wasm